### ISSUE TITLE
nord-theme leaks unprefixed names to the global environment

### ISSUE THREAD

**Issue by slippycheeze** [arcticicestudio/nord-emacs#66]
Sadly, Emacs Lisp has no namespaces, so every top level definition is visible to the entire universe.  That includes variables and functions.

The current nord-theme defines one of each, `nord-brightened-comments` and `brightened-comment-color`, which are leaked.

The former is ... ok, though not best practice.  The later has a chance of conflicting with anything else that uses a similar global name, and is definitely not in line with best practices for Emacs code.

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

That's another point for the „today I learned…“ list!
I've never coded something in (Emacs) Lisp before except this theme so this is a nice info for latter implementations.

**Comment by slippycheeze** [comment]
@arcticicestudio, thank you so much for the work!  I have a few more things on my list to help improve, one key one being at the heart of #59, which I'll submit the same way ... hopefully in the next few days, depending. :)

**Comment by arcticicestudio** [comment]
That's awesome, I'm happy about any help! It bothers me a lot that I could not solve some of the open issues in this repository due to the missing experience with Emacs and the fact that even after searching through many documentations and tutorials not able to find a up-to-date or correct solution. There are also not always ways to reproduce some of the problems.

In short: OSS lives from contributors and I welcome any help for this very much :smile:
