### ISSUE TITLE
show-paren-match face not themed in Emacs 26

### ISSUE THREAD

**Issue by janusvm** [arcticicestudio/nord-emacs#75]
Came across this while adapting my config for Emacs 26.2 coming from 25.3

It seems as if something changed between Emacs versions 25 and 26 wrt. how the names of faces are parsed, which causes the following lines to work fine in Emacs 25, but not 26:

https://github.com/arcticicestudio/nord-emacs/blob/9ed7b9c2d1bb68ae86d06f97d215d2883e4ff0d2/nord-theme.el#L273-L274

seemingly due to the names of the faces not actually having the `-face` suffix.

The same is the case for running `M-x customize-face RET show-paren-match-face RET` - works in 25, not 26, even though the face is really called just `show-paren-match` in both.

In my local `nord-theme.el` on my Emacs 26 installation, I tried changing `show-paren-match-face` to just `show-paren-match` (same for `-mismatch`), and then it worked. I'm not sure if these are the only faces affected by this.

**Comment by janusvm** [comment]
After digging around a bit, I found that `show-paren-match-face` and `show-paren-mismatch-face` were declared as obsolete face aliases for `show-paren-match` and `show-paren-mismatch`, respectively, since version 22.1, and they were then completely removed somewhere in version 25 (commit [`c430f7e23f`](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c430f7e23fc2c22f251ace4254e37dea1452dfc3) on the git repo).

I think this means that dropping the `-face` suffixes would fix the issue for newer versions, but introduce it for versions older than 22.1.

**Comment by arcticicestudio** [comment]
Hi @janusvm :wave:, thanks for your contribution :+1:
Good catch, I've also noticed the defined styles of matching braces changed or respectively aren't respected at all. Thanks a lot for researching the commits and docs!
I guess simply adding the new key names should be fine, there's no need to rename or remove the deprecated ones since Emacs will decide which to use based on the version. This means both versions `<22.1` and `>=22.1` are supported 😄
