### ISSUE TITLE
ivy-mode support

### ISSUE THREAD

**Issue by jdek** [arcticicestudio/nord-emacs#85]
I think this should be relatively similar to `ido`. The relevant faces are (copied from spacemacs-theme):

```elisp
`(ivy-current-match ((,class (:background ,highlight :inherit bold))))
`(ivy-minibuffer-match-face-1 ((,class (:inherit bold))))
`(ivy-minibuffer-match-face-2 ((,class (:foreground ,head1 :underline t))))
`(ivy-minibuffer-match-face-3 ((,class (:foreground ,head4 :underline t))))
`(ivy-minibuffer-match-face-4 ((,class (:foreground ,head3 :underline t))))
`(ivy-remote ((,class (:foreground ,cyan))))
```

**Comment by arcticicestudio** [comment]
Hi @jdek :wave:, thanks for your contribution :+1:
Since I'm not a Emacs user: Is the corresponding GitHub repository [abo-abo/swiper][r] for these faces? I thought _ivy_ was renamed to _swiper_, but after some research _swiper_ seams to be a multi-package repository.

[r]: https://github.com/abo-abo/swiper

**Comment by jdek** [comment]
I think you are correct, I just get it from MELPA (https://melpa.org/#/ivy), which points to that repository. I think Ivy is the main framework thing then swiper and counsel are extensions which build upon it.

**Comment by arcticicestudio** [comment]
Reviewed #87 and added change suggestions.
