### ISSUE TITLE
Some text elements are not colored

### ISSUE THREAD

**Issue by rien333** [arcticicestudio/nord-emacs#93]
Despite what the README shows, integers and other numbers do not get a purple shade, but retain the color of regular text. (tested with multiple files, including a `.go` file, as in the example). The same goes for logical operators like `!=` and `&&`.

Anybody knows why? I'm not familiar enough with emacs themeing mechanisms to say, but could this be a bug?

**Comment by arcticicestudio** [comment]
Hi @rien333 :wave:, thanks for your contribution :+1:
Sorry for that time gap, must have missed this one in my notifications and just found it while cleaning up the 3k+ items in the new GitHub notification center.

Unfortunately I don't remember exactly which packages I've used to take the screenshots since I only setup Emacs for testing purposes of this theme. Maybe the shipped syntax highlighting support for _Go_ wasn't detailed enough so the chances are high that I've used a popular package like [go-mode.el][] in order to get the best highlighting output.
This is almost the same like _Vim_ where the bundled syntax highlighting is only basic and requires advanced plugins like [govim][] or [vim-go][] for great debugging and development experiences.

[govim]: https://github.com/govim/govim
[vim-go]: https://github.com/fatih/vim-go

[go-mode.el]: https://github.com/dominikh/go-mode.el

**Comment by arcticicestudio** [comment]
@rien333 Have you been able to fix the incorrect styles or does the problem still persists?

**Comment by rien333** [comment]
Sorry for not following up on this. The problem "persists", but I think this is due to the fact that you might have done some extra config when you originally took the screenshots shown in the README. By default, emacs [doesn't use syntax highlighting for numerals](http://www.wilfred.me.uk/blog/2014/09/27/the-definitive-guide-to-syntax-highlighting/), no matter which mode you're in. (you provided example screenshots of java and go, and both do not have highlighted numerals on my end).

As such, I don't think there is anything this package can do here.

**Comment by arcticicestudio** [comment]
No problem, I've also replied like 2 months later 😕
I'll check if I can find the test/screenshot configurations I've used for the project assets, but since I don't use Emacs the chance is high that it was the result of a quick copy&paste Google search.

**Comment by rien333** [comment]
Don't worry too much! Most guides online are pretty clear about it: you'll have to install some special mode for this too work (or add some code yourself)
